repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: "v1.12.0"
    hooks:
      - id: helm-docs
        args:
          # Make the tool search for charts only under the `charts` directory
          - --chart-search-root=charts

          # Set the default template to be used
          - --template-files=./README.md.gotmpl

          # Sort the values table based on the order of the values in the charts values file
          - --sort-values-order=file