apiVersion: v2
name: flaresolverr
description: FlareSolverr is a proxy server to bypass Cloudflare and DDoS-GUARD protection.
type: application
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: Brandan Schmitz
    email: brandan.schmitz@celestialdata.net
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
home: https://github.com/brandan-schmitz/helm-charts/flaresolverr
sources:
  - https://github.com/FlareSolverr/FlareSolverr
icon: file://icon.svg
version: 1.2.3
appVersion: 3.3.15
