---
{{- include "bjw-s.common.loader.init" . }}

{{- define "app-template.hardcodedValues" -}}
# Set the nameOverride based on the release name if no override has been set
{{ if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"

controllers:
  bitmagnet:
    containers:
      bitmagnet:
        image:
          tag: "{{ default (printf "v%s" .Chart.AppVersion) .Values.controllers.bitmagnet.containers.bitmagnet.image.tag }}"
{{ end }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "app-template.hardcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}