{
 "title": "Blackhole Manager",
 "tags": [
  "blackhole-manager",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_network_receive_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\"}, namespace)"
    }
   },
   {
    "name": "downloader_workload",
    "label": "Aria2 Downloader Workload",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$namespace\"}, workload)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Base Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Breakdown of Sources",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(radarr_completed) without (instance, container, endpoint, pod, job)",
     "legendFormat": "Radarr"
    },
    {
     "expr": "sum(sonarr_completed) without (instance, container, endpoint, pod, job)",
     "legendFormat": "Sonarr"
    },
    {
     "expr": "sum(manual_completed) without (instance, container, endpoint, pod, job)",
     "legendFormat": "Manual"
    }
   ]
  },
  {
   "title": "Active Sonarr Items",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarr_active) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Radarr Items",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(radarr_active) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Manual Items",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(manual_active) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarr_completed) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blacklisted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarr_blacklisted) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(radarr_completed) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blacklisted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(radarr_blacklisted) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(manual_completed) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blacklisted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(manual_blacklisted) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Sources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarr_completed + radarr_completed + manual_completed) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Files",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarr_files_processed + radarr_files_processed + manual_files_processed) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deleted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarr_deleted) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Files Processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarr_files_processed) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deleted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(radarr_deleted) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Files Processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(radarr_files_processed) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deleted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(manual_deleted) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Files Processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(manual_files_processed) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Filesize Processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 1, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarr_filesize_processed + radarr_filesize_processed + manual_filesize_processed) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesize Processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sonarr_filesize_processed) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesize Processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(radarr_filesize_processed) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesize Processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(manual_filesize_processed) without (instance, container, endpoint, pod, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Historical Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total Active",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(sonarr_active + radarr_active + manual_active) without (instance, container, endpoint, pod, job)",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_receive_bytes_total{metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespace\"}[$__interval:30s]) * on (namespace,pod)\n    group_left(workload,workload_type) \n    namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"plex-system\", workload=~\"$downloader_workload\"}) by (pod))",
     "legendFormat": "Download Speed"
    }
   ]
  },
  {
   "title": "Total Completed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(sonarr_completed + radarr_completed + manual_completed) without (instance, container, endpoint, pod, job)",
     "legendFormat": "Total Completed"
    }
   ]
  }
 ]
}