---
{{- include "bjw-s.common.loader.init" . }}

{{- define "octopus-deploy.commonHardcoded" -}}
global:
  nameOverride: "{{ .Release.Name }}"
controllers:
  main:
    enabled: false
service:
  main:
    enabled: false

{{- if not .Values.settings.existingSecret }}
secrets:
  config:
    {{- if .Values.settings.retain }}
    annotations:
      "helm.sh/resource-policy": "keep"
    {{- end }}
    enabled: true
    stringData:
      DB_CONNECTION_STRING: "Server={{ .Release.Name }}-mssql,1433;Database={{ .Values.settings.databaseName }};User={{ .Values.settings.databaseUser }};Password={{ .Values.settings.databasePassword }}"
      ADMIN_USERNAME: {{ .Values.settings.adminUsername }}
      ADMIN_PASSWORD: {{ .Values.settings.adminPassword }}
      ADMIN_EMAIL: {{ .Values.settings.adminEmail }}
      {{- if .Values.settings.licenseKey }}
      OCTOPUS_SERVER_BASE64_LICENSE: {{ .Values.settings.licenseKey | b64enc | quote}}
      {{- end }}
      MSSQL_SA_PASSWORD: {{ .Values.settings.databasePassword }}
      MASTER_KEY: {{ default .Values.settings.masterKey (include "octopus-deploy.masterKeySecret" . ) }}
{{- end }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "octopus-deploy.commonHardcoded" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}