# Creates the blank keys needed to merge the values below together.
{{- define "octopus-deploy.mssql-base-keys" -}}
controllers:
  mssql:
    pod: {}
    containers:
      main:
        image: {}
        resources: {}
        probes: {}
service:
  mssql: {}
{{- end }}
{{- $_ := mergeOverwrite .Values (include "octopus-deploy.mssql-base-keys" . | fromYaml) -}}

# Merge in values from specific config sections
{{- $_ := mergeOverwrite .Values.controllers.mssql.containers.main.image .Values.mssql.image -}}
{{- $_ := mergeOverwrite .Values.controllers.mssql.pod .Values.mssql.podOverrides -}}
{{- $_ := mergeOverwrite .Values.controllers.mssql.containers.main.resources .Values.mssql.resources -}}
{{- $_ := mergeOverwrite .Values.service.mssql .Values.mssql.service -}}
{{- $_ := mergeOverwrite .Values.controllers.mssql.containers.main.probes .Values.mssql.probes -}}

{{- define "octopus-deploy.mssql-hardcoded" -}}
controllers:
  mssql:
    type: deployment
    strategy: Recreate
    replicas: 1
    pod:
      securityContext:
        fsGroup: 10001
    containers:
      main:
        env:
          - name: ACCEPT_EULA
            value: {{ if .Values.settings.acceptEula }}"Y"{{ else }}"N"{{ end }}
          - name: MSSQL_PID
            value: "Express"
          - name: MSSQL_IP_ADDRESS
            value: "0.0.0.0"
          - name: MSSQL_TCP_PORT
            value: "1433"
          - name: MSSQL_SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ default .Values.settings.existingSecret (printf "%s-config" .Release.Name) }}
                key: MSSQL_SA_PASSWORD
        probes:
          liveness:
            custom: false
            type: TCP
          readiness:
            custom: false
            type: TCP
          startup:
            custom: false
            type: TCP
service:
  mssql:
    controller: mssql
    primary: true
    nameOverride: "mssql"
    ports:
      http:
        enabled: false
      mssql:
        primary: true
        targetPort: 1433
        protocol: TCP

persistence:
  mssql-data:
    enabled: {{ .Values.mssql.storage.enabled }}
    storageClass: {{ .Values.mssql.storage.storageClass }}
    existingClaim: {{ .Values.mssql.storage.existingClaim | default "" }}
    accessMode: {{ .Values.mssql.storage.accessMode }}
    size: {{ .Values.mssql.storage.size }}
    retain: {{ .Values.mssql.storage.retain }}
    advancedMounts:
      mssql:
        main:
          - path: /var/opt/mssql
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "octopus-deploy.mssql-hardcoded" . | fromYaml) -}}