apiVersion: v2
name: radarr
description: A fork of Sonarr to work with movies à la Couchpotato.
type: application
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: Brandan Schmitz
    email: brandan.schmitz@celestialdata.net
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 1.5.1
home: https://github.com/brandan-schmitz/helm-charts/tree/master/radarr
sources:
  - https://github.com/linuxserver/docker-radarr
  - https://github.com/Radarr/Radarr
icon: https://raw.githubusercontent.com/brandan-schmitz/helm-charts/master/charts/radarr/icon.png
version: 2.9.0
appVersion: 5.23.3.9987